pipeline
{
    agent any

    tools {
        nodejs "24.12.0"   // Use the Node version name you configured in Jenkins
    }

    stages
    {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        //stage('Install Dependencies') {
        //    steps {
        //        sh 'npm install'
        //    }
        //}

        stage('Build Angular 21 App') {
            steps {
                sh 'npm run build --prod'
            }
        }

        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'dist/**', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying build...'
                // Add your deployment commands here
                // Example:
                // sh 'scp -r dist/ user@server:/var/www/html'
            }
        }
    }

    triggers {
        githubPush()   // Trigger when code is pushed
    }
}